name: rixtretto-server

services:
  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    command: 'postgres -c log_statement=all -c log_destination=stderr'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./adminer-plugins
        target: /var/www/html/plugins-enabled
    environment:
      ADMINER_DEFAULT_SYSTEM: pgsql
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_NAME: ${DB_USER}
      ADMINER_DEFAULT_PASS: ${DB_PASSWORD}
      ADMINER_DEFAULT_DATABASE: ${DB_NAME}
      ADMINER_AUTOLOGIN_AUTOSUBMIT: false

volumes:
  db-data:
