"""service_coffee_association

Revision ID: d519f4fd67ea
Revises: 0258dd319617
Create Date: 2026-09-12 16:21:51.022568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d519f4fd67ea"
down_revision: Union[str, Sequence[str], None] = "0258dd319617"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_coffee_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("roasted_coffee_id", sa.Integer(), nullable=False),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="e.g. coffeeshop, popup, restaurant",
        ),
        sa.Column("details", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("date_added", sa.DateTime(), nullable=True),
        sa.Column("date_removed", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["roasted_coffee_id"],
            ["roasted_coffees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "green_coffees",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Green coffees without an assigned name refer to generic/unknown coffee of the specified region.",
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("ck_component_or_origin"), "roasted_coffee_components", type_="check"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_component_or_origin"),
        "roasted_coffee_components",
        "NOT (green_id IS NOT NULL AND origin_id IS NOT NULL)",
    )
    op.alter_column(
        "green_coffees",
        "name",
        existing_type=sa.VARCHAR(),
        comment="Green coffees without an assigned name refer to generic/unknown coffee of the specified region.",
        existing_nullable=False,
    )
    op.drop_table("service_coffee_associations")
    # ### end Alembic commands ###
