"""create tables service locations

Revision ID: 7eed3bfc711a
Revises: 15496868c175
Create Date: 2026-07-31 13:55:36.826193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eed3bfc711a'
down_revision: Union[str, Sequence[str], None] = '15496868c175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roaster_id', sa.Integer(), nullable=True, comment='If service has an established relationship with a roaster.'),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False, comment='`name` column normalized to remove case, accents, punctuation'),
    sa.ForeignKeyConstraint(['roaster_id'], ['roasters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_location_associations',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('address_detail', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True, comment="The company's name of the specific location or event"),
    sa.Column('description', sa.String(), nullable=True, comment='e.g. coffeeshop, popup, restaurant'),
    sa.Column('date_opened', sa.DateTime(), nullable=True),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_location_associations')
    op.drop_table('service')
    op.drop_table('locations')
    # ### end Alembic commands ###
