"""create tables menu_items, variants, ingredients

Revision ID: 0258dd319617
Revises: 7eed3bfc711a
Create Date: 2026-08-01 18:42:06.438102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0258dd319617'
down_revision: Union[str, Sequence[str], None] = '7eed3bfc711a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_ingredients',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=False, comment='`name` column normalized to remove case, accents, punctuation'),
    sa.ForeignKeyConstraint(['parent_name'], ['menu_item_ingredients.normalized_name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('normalized_name')
    )
    op.create_table('menu_items',
    sa.Column('service_id', sa.Integer(), nullable=False, comment='for specialty drinks limited to specific retailer'),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_removed', sa.DateTime(), nullable=True, comment='For when a specialty drink is a limited time offering.'),
    sa.Column('details', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False, comment='`name` column normalized to remove case, accents, punctuation'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('normalized_name', 'service_id')
    )
    op.create_table('menu_item_ingredient_associations',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_pkey', sa.String(), nullable=False),
    sa.Column('ingredient_pkey', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['ingredient_pkey'], ['menu_item_ingredients.normalized_name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id', 'menu_item_pkey'], ['menu_items.service_id', 'menu_items.normalized_name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('service_id', 'menu_item_pkey', 'ingredient_pkey')
    )
    op.create_table('menu_item_variants',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_pkey', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id', 'menu_item_pkey'], ['menu_items.service_id', 'menu_items.normalized_name'], ),
    sa.PrimaryKeyConstraint('service_id', 'menu_item_pkey', 'variant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_variants')
    op.drop_table('menu_item_ingredient_associations')
    op.drop_table('menu_items')
    op.drop_table('menu_item_ingredients')
    # ### end Alembic commands ###
