type CoffeeService {
  id: ID
  name: String
  roaster: Roaster
  locations: [CoffeeServiceLocation!]

  menu: [MenuItem]!
}

type CoffeeServiceLocation {
  name: String
  description: String
  location: Location

  dateOpened: String
  dateClosed: String
}

type MenuItem {
  name: String
  service: CoffeeService!

  variants: [String]!
  recipe: [Ingredient!]

  dateAdded: String
  dateRemoved: String
  details: JSON
}

type Ingredient {
  name: String!
  parent: Ingredient
  children: [Ingredient]!
  ancestors: [Ingredient]!
  descendants: [Ingredient]!

  menuItems: [MenuItem]!
}
