type CoffeeService {
  id: ID
  name: String
  roaster: Roaster
  locations: [CoffeeServiceLocation!]

  "Menu of drinks available in service."
  menu: [MenuItem]!

  "Menu of roasted coffees in service."
  coffees: [RoastedCoffee]!

  "List of origins of roasted coffees in service."
  origins: [Origin]!

  "List of processes of component green coffees of roasted coffees in service."
  processes: [String]!

  "List of varieties of component green coffees of roasted coffees in service."
  varieties: [String]!
}

type CoffeeServiceLocation {
  name: String
  description: String
  location: Location

  dateOpened: String
  dateClosed: String
}

type MenuItem {
  name: String
  service: CoffeeService!

  variants: [String]!
  recipe: [Ingredient!]

  dateAdded: String
  dateRemoved: String
  details: JSON
}

type Ingredient {
  name: String!
  parent: Ingredient
  children: [Ingredient]!
  ancestors: [Ingredient]!
  descendants: [Ingredient]!

  menuItems: [MenuItem]!
}
